[feat/task1 38] react-quill examples
team-208/colon-front pull request #19
Opened 2024-04-13 05:25 UTC by ohdal

작업내용.
- feat: react-quill, highlight.js 의존성 설치
- feat: QuillEditor.tsx 컴포넌트 작성 및 QuillEditor 예제 페이지 추가.
- feat: createTextFile 유틸 함수 추가.
- feat: global.css strong, em 태그 css 작성

참고사항.
- QuillEditor 컴포넌트를 사용하는 컴포넌트도 rcc로 동작할 것 같아서 dynamic import 하는 부분을 제거하였습니다.
- QuillEditor toolbar에 사용할 수 있는 기능을 우선 모두 넣어놓았습니다.
- content 내용을 .txt 파일로 변환하는 과정에서 파일명을 논의해 봐야할 것 같습니다.
- storage에서.txt 파일을 가져오는 과정에 대해서 논의해 봐야할 것 같습니다. posts db에서 데이터를 가져올때 서버측에서 storage에서 파일을 불러와 같이 보내주면 좋을것 같은데 가능한지 찾아보겠습니다 :)
- bold, italic 처리 안되었던 부분에 대해서 찾아봤는데, gloabal.css 에서 `font: inherit;` 하는 부분에서 뭔가 덧씌워져서 <strong>, <em> 태그가 제대로 동작하지 않았습니다. 해당 태그의 css를 다시 작성해주는게 괜찮겠다고 생각해서 게시판 페이지나, 작성, 수정시 모두를 고려해서 global.css에  추가하였습니다.

2024-04-13 12:37 UTC, huun0424 reviewed
comment 확인 부탁드립니다. 🙇‍♂️

2024-04-13 12:37 UTC, huun0424 commented on app/(pages)/examples/quilleditor/page.tsx
> +import QuillEditor from '@/app/components/common/QuillEditor';
dynamic으로 import 하지 않으면, pre-rendering이 되지 않아서 build fail이 됩니다. editor 가 포함된 컴포넌트는 이벤트나 사용자 인터렉션이 필요해서 rcc로 동작하는게 좋을듯 해요.

2024-04-13 12:37 UTC, huun0424 commented on app/components/common/QuillEditor.tsx
> +      editorInstance.current = new Quill('#container', options);
ref와 jquery로 editorInstance를 생성하고 설정하셨는데, RactQuill tag 사용시 이슈가 있어서 안쓰신걸까요?

2024-04-13 12:39 UTC, huun0424 commented
- storage에서.txt 파일을 가져오는 과정에 대해서 논의해 봐야할 것 같습니다. posts db에서 데이터를 가져올때 서버측에서 storage에서 파일을 불러와 같이 보내주면 좋을것 같은데 가능한지 찾아보겠습니다 :)

-> 요건 가능합니다. get api 작업시 post 정보와 함께 text file 보내도록 할게요 :)

2024-04-15 04:23 UTC, ohdal commented on app/(pages)/examples/quilleditor/page.tsx
> +import QuillEditor from '@/app/components/common/QuillEditor';
아 네넵 그렇네요! 알겠습니다. 맞아요 이벤트랑 필요해서 editor가 포함된 컴포넌트는 rcc로 동작해야 할 것 같아요 ! dynamic import로 다시 수정하겠습니당 🙇🏻‍♀️

2024-04-15 05:33 UTC, ohdal commented on app/components/common/QuillEditor.tsx
> +      editorInstance.current = new Quill('#container', options);
Quilljs 홈페이지 Document 예제를 참고해서 하다보니..! 이슈가 있어서 안쓴건 아닙니다 ㅜㅜ 너무 의식의 흐름대로 했네요.. ReactQuill tag 사용으로 수정하는게 좋을것 같네요 ! 감사합니다 수정하겠습니당

2024-04-16 12:02 UTC, huun0424 reviewed
리뷰 확인 부탁드립니다.

2024-04-17 00:20 UTC, ohdal commented on app/components/common/QuillEditor.tsx
> +        <ReactQuill {...options} ref={editorRef} />
네 그렇네요 !! 감사합니다 수정하겠습니다 👍🏻

2024-04-17 05:34 UTC, huun0424 approved these changes
옙 어프로브 했습니다 :)

2024-04-17 12:58 UTC, huun0424 requested changes
기획서 보고나니 수정할 부분이 생겼습니다. 확인 부탁드립니다. 🙇‍♂️

2024-04-18 05:26 UTC, ohdal commented on app/components/common/QuillEditor.tsx
> +        <ReactQuill {...options} ref={editorRef} defaultValue={initValue} />
넵넵 ReactQuill 문서 다시 꼼꼼히 읽어보겠습니다.. 감사합니당 🙇🏻‍♀️

2024-04-18 18:21 UTC, ohdal commented on app/components/common/QuillEditor.tsx
> +    debounce((v: ReactQuill.Value) => {
미리보기용 텍스트 추출로직 예제페이지에 추가하였습니다 🙇🏻‍♀️

2024-04-18 18:22 UTC, merged